### ISSUE TITLE
About the training hyper parameters.

### ISSUE THREAD

**Issue by xinyu-site** [ElisevanderPol/marl_homomorphic_networks#1]
Thank you for the great work. I am really interested in your holomorphic network. However, I ran into some issues when trying to run your code. I ran wildlife_ppo.py with the default hyperparameters, but the training failed to converge and the average return remained around -5. Can you please provide some insight into why this might be happening?

**Comment by xinyu-site** [comment]
I noticed that you included ./scripts/test_wildlife.sh in the readme, but I can't seem to find the file. Is it possible that the file has been moved or deleted? If so, could you provide an updated location or file name for the script?

**Comment by ElisevanderPol** [comment]
Hi, thank you for your interest in our work and for letting me know about the missing files! The missing scripts are now included in `examples/scripts/`, if this does not resolve the issue please feel free t reopen the issue.
